version: "3.9"
services:
  postgres:
    image: "postgres:14-alpine"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bnmo
    restart: always
  redis:
    image: "redis:7.0"
    environment:
      REDIS_PASSWORD: redis
  backend:
    build: .
    depends_on:
      - redis
      - postgres
    ports:
      - "3001:3000"
    volumes:
      - backend:/app
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DBNAME: bnmo
      DB_PORT: 5432
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      SECRET: secrekt
    restart: always
    entrypoint: ["/app/scripts/wait-for", "postgres:5432", "--","/app/server"]
volumes:
  postgres:
  backend: