version: "3.9"
services:
  postgres:
    image: "postgres:14-alpine"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bnmo
    restart: always
  redis:
    image: "redis:7.0"
    environment:
      REDIS_PASSWORD: redis
  backend:
    build: .
    depends_on:
      - redis
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - backend:/app
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DBNAME: bnmo
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      SECRET: secrekt
      API_KEY: EnIvvlHCDvaZ9O83l58PAptuiN9VMIoc
      WAIT_HOSTS: redis:6379, postgres:5432
    restart: always
volumes:
  postgres:
  backend: